apiVersion: v1
kind: Service
metadata:
  namespace: dash-ecomm
  name: rasa-actions
spec:
  ports:
    - name: rasa-actions-port
      port: 5055
      targetPort: 5055
  selector:
    component: rasa-actions
  type: ClusterIP