apiVersion: v1
kind: Service
metadata:
  namespace: dash-ecomm
  name: elasticsearch
spec:
  ports:
    - name: elasticsearch-port
      port: 9200
      targetPort: 9200
    - name: elasticsearch-manager-port
      port: 9300
      targetPort: 9300
  selector:
    component: elasticsearch
  type: ClusterIP