apiVersion: v1
kind: Service
metadata:
  namespace: dash-ecomm
  name: duckling
spec:
  ports:
    - name: duckling-port
      port: 8000
      targetPort: 8000
  selector:
    component: duckling
  type: ClusterIP