apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-event-consumer
  namespace: dash-ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rasa-event-consumer
      type: dash-ecomm
  template:
    metadata:
      labels:
        component: rasa-event-consumer
        type: dash-ecomm
    spec:
      containers:
      - image: textclouddev.azurecr.io/neuralspace/dash-ecomm:latest
        imagePullPolicy: Always
        command: ["poetry", "run", "python", "-m", "dash_ecomm.pika_event_consumer", "--rmq-host", "rabbitmq", "--es-host", "http://elasticsearch:9200/"]
        name: dash-ecomm-rasa-event-consumer
        resources:
          requests:
            cpu: 0.2
            memory: 100Mi
      initContainers:
      - name: rasa-prod-running
        image: curlimages/curl:7.75.0
        command: ["curl", "--retry", "10", "--retry-connrefused", "http://rasa-prod:5005"]
      restartPolicy: Always
