apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: dash-ecomm
spec:
  secretName: tls-secret
  dnsNames:
  - ns-botlibrary-ecomm.uksouth.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ns-botlibrary-ecomm.uksouth.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
