apiVersion: v1
kind: Service
metadata:
  namespace: dash-ecomm
  name: callback-server
spec:
  ports:
    - name: callback-server-port
      port: 5054
      targetPort: 5054
  selector:
    component: callback-server
  type: ClusterIP