apiVersion: v1
kind: Service
metadata:
  namespace: dash-ecomm
  name: rabbitmq
spec:
  ports:
    - name: rabbitmq-port
      port: 5672
      targetPort: 5672
    - name: rabbitmq-manager-port
      port: 15672
      targetPort: 15672
  selector:
    component: rabbitmq
  type: ClusterIP